### ISSUE TITLE
Using the software

### ISSUE THREAD

**Issue by Yakrel** [Uranium2/Auto_Hekili#1]
Hi I am trying to install it but I am stuck at these steps
$> python3 -m venv .venv
$> .venv\Script\activate
(.venv) $> pip3 install -r requirements.txt

I did try it both wsl and windows, on windows I am not even sure how to make this command work on terminal, on wsl after this step
"python3 -m venv .venv" nothing happens.

**Comment by Uranium2** [comment]
I think I was using python3.8 for this project in windows.
The syntax for venv is a bit different if you use WSL

I can use this program without venv, but I think it is a good practice to use venv (or conda if you're more used to it) so you don't mess up your global python. https://docs.python.org/3/library/venv.html

Some installation of python uses the syntax "py", "py3", "python" "python3" or even with version "python3.X". Depends on your installation.

Note that this code was made during W.o.W Shadowlands, and might not work well with other versions. You will need to update images if spells changes. Or even create a new folder for new class.
You also need to update `config/Notes` folder to add new simc files to list all spells of each class. And in file `src/utils.py` update the code if the spell in <class>.smic does not correspond to the correct in game spell name.

        if class_spec == "Hunter_BeastMastery":
            spells = edit_spell_list(spells, None, {"multishot": "multi-shot"})
            
  Here `multishot` is the spell in the file name, but in the game it is called `multi-shot`
